const { JSONModel } = require( "./index" );

const schema = {
  "title": "Event Group",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Auto generated by backend"

    },
    "name": {
      "type": "string",
      "error_messages": { "required": "name is required" }
    },
    "description": {
      "type": "string",
      "error_messages": { "required": "Description is required" }
    },
    "apple_directory_group": {
      "type": "string",
      "error_messages": { "required": "User group is required" }
    },
    "prefix": {
      "type": "string",
      "error_messages": { "required": "Prefix is required" }
    }
  },
  "required": [ "name", "description", "apple_directory_group", "prefix" ]
};

const props = {
  "idProp": "id",
  "url": "http://localhost:9000/api/v1/event_group",
  "parseInstanceProp": "result",
  "parseListProp": "result"
};

let eventGroup = new JSONModel( schema, props );
eventGroup.name = "Sample event Group";
eventGroup.description = "Sample event Group description";
eventGroup.apple_directory_group = "Sample user Group";
eventGroup.prefix = "Sample event Group prefix";
// eventGroup.save().then( savedEventGroup => console.log( savedEventGroup ) ).catch( err => console.log( err ) );

JSONModel.find( "58e57b2de10000e1006b21fb", schema, props ).then( e => console.log( e ) ).catch( err => console.log( err ) );
// JSONModel.find({}, schema, props ).then( e => console.log( e[0].author ) ).catch( err => console.log( err ) );